site_name: "Kurisu's life"
site_url: https://mydomain.org/mysite
theme:
  name: material
  logo: 
  theme:
  palette: 


  

    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy


plugins:
  - search
  - tags
  - blog
    

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences



nav:
   - Home: index.md
   - Biografia: 
       - Qualcosa su di me: biografia/about.md
       - Cosa frequento: biografia/childhood.md
       - canali: biografia/project.md
   - Codici:
       - Python: coding/my-first-python-file.md
   - Tags: tags.md
   - Blog: blog/index.md
   - Documentazione: 
      - Sopralluoghi: Documentazione/Soprallughi.md
      - Progetto principale: Documentazione/Progetto.md
      - Cosa ho fatto oggi: Documentazione/Cosa-ho-fatto-oggi.md
      - Foto progetto: Documentazione/Foto-progetto.md

extra_css:
  - assets/style.css